"""Initial migration.

Revision ID: 253470b891ca
Revises: 
Create Date: 2020-10-29 02:07:04.115137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '253470b891ca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('dni', sa.String(length=9), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('genero', sa.Enum('hombre', 'mujer', 'otro'), nullable=False),
    sa.PrimaryKeyConstraint('client_id'),
    sa.UniqueConstraint('dni')
    )
    op.create_table('motos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.Enum('AVAILABLE', 'RESERVED', 'ACTIVE', 'REPAIRING', 'LOW_BATTERY_FUEL', 'UNREPAIRABLE', 'UNCHECKED', 'ACCIDENT'), nullable=False),
    sa.Column('matricula', sa.String(length=30), nullable=False),
    sa.Column('date_estreno', sa.String(length=30), nullable=False),
    sa.Column('model_generic', sa.String(length=10), nullable=False),
    sa.Column('model_fabric', sa.String(length=10), nullable=False),
    sa.Column('cc', sa.Integer(), nullable=False),
    sa.Column('battery_autonomy', sa.Integer(), nullable=False),
    sa.Column('last_coordinate_latitude', sa.Float(), nullable=False),
    sa.Column('last_coordinate_longitude', sa.Float(), nullable=False),
    sa.Column('km_restantes', sa.Float(), nullable=False),
    sa.Column('km_totales', sa.Float(), nullable=False),
    sa.Column('date_last_check', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relations_table',
    sa.Column('clients', sa.Integer(), nullable=True),
    sa.Column('motos', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clients'], ['clients.client_id'], ),
    sa.ForeignKeyConstraint(['motos'], ['motos.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relations_table')
    op.drop_table('motos')
    op.drop_table('clients')
    # ### end Alembic commands ###
