"""Initial migration

Revision ID: 2cc8a7c8cb50
Revises: 
Create Date: 2020-10-27 17:41:11.004079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cc8a7c8cb50'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('dni', sa.String(length=9), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('genero', sa.Enum('hombre', 'mujer', 'otro'), nullable=False),
    sa.PrimaryKeyConstraint('client_id'),
    sa.UniqueConstraint('dni')
    )
    op.create_table('motos',
    sa.Column('moto_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('ready', 'reserved', 'broken', 'garage'), nullable=True),
    sa.Column('km_totales', sa.Float(), nullable=False),
    sa.Column('km_ultima_revision', sa.Float(), nullable=False),
    sa.Column('fecha_ultima_revision', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('moto_id')
    )
    op.create_table('relations_table',
    sa.Column('clients', sa.Integer(), nullable=True),
    sa.Column('motos', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clients'], ['clients.client_id'], ),
    sa.ForeignKeyConstraint(['motos'], ['motos.moto_id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relations_table')
    op.drop_table('motos')
    op.drop_table('clients')
    # ### end Alembic commands ###
